# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-23 08:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Classification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.CharField(max_length=100)),
                ('label', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Modification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.IntegerField()),
                ('date', models.DateTimeField(verbose_name='date modified')),
                ('from_label', models.CharField(max_length=40)),
                ('to_label', models.CharField(max_length=40)),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='annotations.Classification')),
            ],
        ),
    ]
