# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-23 08:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('annotations', '0004_auto_20161023_1646'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Dataset',
            new_name='ImageLabel',
        ),
    ]
