# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-24 02:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotations', '0005_auto_20161023_1647'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagelabel',
            name='image',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='modification',
            name='date',
            field=models.DateTimeField(db_index=True, verbose_name='date modified'),
        ),
    ]
