# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-24 08:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotations', '0007_auto_20161024_0825'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modification',
            name='image',
            field=models.CharField(db_index=True, max_length=100),
        ),
    ]
